format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$deno\
$dotnet\
$golang\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$fill\
$memory_usage\
$time\
$cmd_duration\
$line_break\
$os\
$jobs\
$battery\
$status\
$container\
$shell\
$character"""

[os]
disabled = false

[username]
style_user = 'yellow bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false

[kubernetes]
disabled = true

[directory]
read_only = " "
truncate_to_repo = true
truncation_length = 8
truncation_symbol = ''
repo_root_style = 'cyan'
style = 'bold cyan'

[git_branch]
symbol = " "

[git_commit]
tag_symbol = " "
tag_disabled = false
only_detached = false
style = 'purple'

[git_status]
format = "$all_status$ahead_behind "

[docker_context]
symbol = " "
format = 'via [$symbol $context](blue bold)'

[package]
symbol = " "
format = "is [$symbol$version]($style) "
display_private = true

[c]
symbol = " "

[deno]
symbol = "🦕"

[dotnet]
symbol = " "

[golang]
symbol = " "

[nodejs]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[aws]
symbol = "  "
disabled = true

[azure]
symbol = "ﴃ  "

[buf]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[pijul_channel]
symbol = "🪺 "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[fill]
symbol = " "

[time]
disabled = false
time_format = "%R"
format = "[$time]($style) "

[memory_usage]
disabled = false
symbol = " "
format = "[$symbol$ram]($style) "

[battery]
full_symbol = ' '
charging_symbol = ' '
discharging_symbol = ' '

[cmd_duration]
format = "took [$duration]($style) "
show_milliseconds = true
